//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Course_Schedule = new HashSet<Course_Schedule>();
            this.Student_Bill = new HashSet<Student_Bill>();
            this.Student_Course = new HashSet<Student_Course>();
        }
    
        public int CourseId { get; set; }
        public string CourseName { get; set; }
    
        public virtual Course_Detail Course_Details { get; set; }
        public virtual ICollection<Course_Schedule> Course_Schedule { get; set; }
        public virtual ICollection<Student_Bill> Student_Bill { get; set; }
        public virtual ICollection<Student_Course> Student_Course { get; set; }
    }
}
